# Run backend test.

name: backend-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    env:
      MOC_VERSION: 0.6.18
      VESSEL_VERSION: v0.6.2
      DFX_VERSION: 0.8.4
    steps:
      - uses: actions/checkout@v2
      - uses:  aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.4
          install-moc: true
          vessel-version: 0.6.2
      - name: show version
        run: |
          dfx --version
          moc --version
          vessel --version
      - name: install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          wasmtime -V
      - name: module test
        run: |
          make module_test
      - name: canister test
        run: |
          dfx start --background
          dfx deploy --no-wallet todo_ic
          make canister_test
          dfx stop
