# Run backend test.

name: backend-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    env:
      VESSEL_VERSION: 0.6.2
      DFX_VERSION: 0.9.0
      WASMTIME_VERSION: 0.33.0
      BACKEND_CANISTER: todo_ic
    steps:
      - uses: actions/checkout@v2
      - name: install dfx/moc/vessel
        uses:  aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: ${{ env.DFX_VERSION }}
          install-moc: true
          vessel-version: ${{ env.VESSEL_VERSION }}
      - name: install wasmtime
        uses: mwilliamson/setup-wasmtime-action@v1
        with:
          wasmtime-version: ${{ env.WASMTIME_VERSION }}
      - name: show versions
        run: |
          dfx --version
          moc --version
          vessel --version
          wasmtime -V
      - name: motoko type checking
        run: |
          for i in src/${{ env.BACKEND_CANISTER }}/*.mo ; do $(dfx cache show)/moc $(vessel sources) --check $i ; done
      - name: module test
        run: |
          make module_test
      - name: canister test
        run: |
          dfx start --background
          dfx deploy --no-wallet ${{ env.BACKEND_CANISTER }}
          make canister_test
          dfx stop
