# Run frontend test.

name: frontend-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm login --registry=https://npm.pkg.github.com --scope=@Psychedelic
          npm install
      - name: Run jest
        run: npm test
