# Run frontend test.

name: frontend-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm-cli-login
        run: npm install -g npm-cli-login
      - name: Login npm
        run: npm-cli-login -u ${{ secrets.USER_NAME }} -e ${{ secrets.EMAIL }} -p ${{ secrets.GITHUB_TOKEN }} -r https://npm.pkg.github.com -s @Psychedelic
      - name: npm install
        run: |
          npm login --registry=https://npm.pkg.github.com --scope=@Psychedelic
          npm install
      - name: Run jest
        run: npm test
